/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica.pkg9;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Bautista
 */
public class ventanaBorrar extends javax.swing.JFrame {

   
    ArrayList<String> txtIdiomas=new ArrayList<String>();
    ArrayList<Disco> datos=new ArrayList<Disco>();
    String idioma;
    int nIdiomas;
    int indiceIdioma;
    
    /////////////////////////CONSTRUCTOR///////////////////////////////////
    public ventanaBorrar(ArrayList<Disco> _datos,ArrayList<String> _idiomas,String _idioma) {
        initComponents();
        datos=_datos;
        txtIdiomas=_idiomas;
        idioma=_idioma;
        setResizable(false);
        traducir();
    }
    ///////////////////////////FUNCIONES/////////////////////////////////
     public void traducir(){
        System.out.println(idioma);
        for(int i=0;i<txtIdiomas.size();i++){
           if(idioma.equals(txtIdiomas.get(i))){
               indiceIdioma=i;
               jButton1.setText(txtIdiomas.get(i+3));
               jButton2.setText(txtIdiomas.get(i+5));
               jLabel1.setText(txtIdiomas.get(i+18));
                    
           }
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo2.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 277, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(327, 327, 327))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(303, 303, 303))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(53, 53, 53)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/////////////////////////////BOTONES///////////////////////////////
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        
        ventanaInicial v = null;
        try {
            v = new ventanaInicial(datos,idioma);
        } catch (IOException ex) {
            Logger.getLogger(ventanaBorrar.class.getName()).log(Level.SEVERE, null, ex);
        }
        v.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().isEmpty()){
            JOptionPane.showOptionDialog(null, txtIdiomas.get(indiceIdioma+11), //contenido de la ventana
txtIdiomas.get(indiceIdioma+23) , //titulo de la ventana
                         JOptionPane.YES_OPTION, //para 3 botones si/no/cancel
                         JOptionPane.ERROR_MESSAGE, //tipo de ícono
                         null,    // null para icono por defecto.
                         new Object[] { txtIdiomas.get(indiceIdioma+16) },
                         null); //selección predeterminada
        }else{
            if(datos.size()-1<Integer.parseInt(jTextField1.getText())){
                JOptionPane.showOptionDialog(null, txtIdiomas.get(indiceIdioma+12), //contenido de la ventana
txtIdiomas.get(indiceIdioma+23) , //titulo de la ventana
                         JOptionPane.YES_OPTION, //para 3 botones si/no/cancel
                         JOptionPane.ERROR_MESSAGE, //tipo de ícono
                         null,    // null para icono por defecto.
                         new Object[] { txtIdiomas.get(indiceIdioma+16) },
                         null); //selección predeterminada
        
            }else{
                 int a=JOptionPane.showOptionDialog(null, txtIdiomas.get(indiceIdioma+9)+" "+datos.get(Integer.parseInt(jTextField1.getText())).nombre+ " ?", //contenido de la ventana
txtIdiomas.get(indiceIdioma+22) , //titulo de la ventana
                         JOptionPane.YES_NO_OPTION, //para 3 botones si/no/cancel
                         JOptionPane.INFORMATION_MESSAGE, //tipo de ícono
                         null,    // null para icono por defecto.
                         new Object[] { txtIdiomas.get(indiceIdioma+24),txtIdiomas.get(indiceIdioma+25) },
                         null); //selección predeterminada
                 if(a==0){//si
                    datos.remove(Integer.parseInt(jTextField1.getText()));
                    
                    ventanaInicial v = null;
                     try {
                         v = new ventanaInicial(datos,idioma);
                    } catch (IOException ex) {
                    Logger.getLogger(ventanaBorrar.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    v.setVisible(true);
                     dispose();
                 }
                  
            }
           
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
